# -*- coding: utf-8 -*-
"""Copy of Real Time Vehicle Detection & Traffic flow Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8OBu6_oYbKj0n68ENNbwFA1_RhXKZ2q
"""

!pip install ultralytics # Install the ultralytics package
from ultralytics import YOLO
import cv2

# Load pre-trained YOLO model
model = YOLO("yolov5s.pt")  # Small model

# Load an image
image_path = "/content/test_image.jpg"
image = cv2.imread(image_path)

# Run detection
results = model(image)

# Show results
for result in results:
    result.show()  # Display detected vehicles

from google.colab import files
uploaded = files.upload()

model = YOLO("yolov8n.pt")
results = model("/content/test_image.jpg", show=True)

model = YOLO("yolov8n.pt")
results = model("test_image.jpg", show=True)

import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

# Load the YOLO model
model = YOLO("yolov8n.pt)
results = model("/content/test_image.jpg")

img = cv2.imread("/content/test_image.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Display the image
plt.imshow(img)
plt.axis("off")
plt.show()

from ultralytics import YOLO
import cv2

# Load YOLO model
model = YOLO("yolov8n.pt")  # Use 'yolov8s.pt' or 'yolov8m.pt' for better accuracy

# Run detection on a video
results = model("/content/traffic video.mp4", save=True, show=False)  # Change path if needed

# Display results
for r in results:
    r.show()  # Show output (Works only in local environments)

from collections import deque

# store vehicle count
vehicle_count = deque(maxlen=100)
def count_vehicles(results):
    global vehicle_count
    for r in results:
        for box in r.boxes:
            if box.cls == 2 or box.cls == 7:
                vehicle_count.append(1)
    print("Total Vehicles:", len(vehicle_count))

from IPython.display import display, Video

# Process video and save output
results = model("/content/traffic video.mp4", save=True, stream=True)

# Show saved video
output_path = "/content/runs/detect/predict/traffic footage.mp4"
display(Video(output_path, embed=True))

for i, r in enumerate(results):
    car_count = sum(r.boxes.cls.cpu().numpy() == 2)
    bus_count = sum(r.boxes.cls.cpu().numpy() == 5)
    print(f"Frame {i + 1}: Cars = {car_count}, Buses = {bus_count}")

from ultralytics import YOLO
import cv2
import pandas as pd


model = YOLO("yolov8n.pt")

results = model("/content/traffic video.mp4", save=True, show=False)

data = []
for i, r in enumerate(results):
    car_count = sum(r.boxes.cls.cpu().numpy() == 2)
    bus_count = sum(r.boxes.cls.cpu().numpy() == 5)
    data.append([i + 1, car_count, bus_count])


df = pd.DataFrame(data, columns=["Frame", "Cars", "Buses"])


df.to_csv("traffic_analysis.csv", index=False)

# Download the CSV file
from google.colab import files
files.download("traffic_analysis.csv")

import os
print(os.listdir("runs/detect/"))

print(os.listdir("runs/detect/predict2"))

import cv2
from ultralytics import YOLO

# Load pre-trained YOLOv8 model
model = YOLO("yolov8n.pt")

def detect_vehicles_in_frame(frame):

    results = model(frame)


    vehicle_count = 0
    for result in results:
        for box in result.boxes:
            # Check if detected object is a vehicle
            if box.cls in [2, 3, 5, 7]:
                vehicle_count += 1

    return vehicle_count

import os

# Check the contents of the prediction folder
path = "/content/runs/detect/predict/"
print(os.listdir(path))

import cv2

# Load the processed video
video_path = "/content/runs/detect/predict/traffic video.avi"
cap = cv2.VideoCapture(video_path)

frame_count = 0
total_vehicles = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    frame_count += 1


    vehicle_count = detect_vehicles_in_frame(frame)
    total_vehicles += vehicle_count

    print(f"Frame {frame_count}: {vehicle_count} vehicles detected")

cap.release()
print(f"Total Vehicles Detected: {total_vehicles}")

from google.colab.patches import cv2_imshow
import cv2

cap = cv2.VideoCapture("/content/traffic_fixed.avi")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    cv2_imshow(frame)

    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

if total_vehicles < 10:
    print("Low Traffic 🚦")
elif 10 <= total_vehicles < 30:
    print("Moderate Traffic 🚗🚙")
else:
    print("Heavy Traffic 🚛🚚🚙🚗")

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("/content/traffic_analysis (17).csv")

print(df.head())

import pandas as pd

csv_path = "/content/traffic_analysis (17).csv"
df = pd.read_csv(csv_path)

print(df.info())
print(df.head())

# Fill missing values with the median
df.fillna(df.median(), inplace=True)

df.drop_duplicates(inplace=True)

print("Data after cleaning:", df.info())

import pandas as pd
csv_path = "/content/traffic_analysis (17).csv"
df = pd.read_csv(csv_path)

print(df.columns)

df.columns = df.columns.str.strip()

df.rename(columns={'actual_column_name': 'frame_number'}, inplace=True)

import matplotlib.pyplot as plt

# Calculate total vehicle count (if needed)
df["vehicle_count"] = df["Cars"] + df["Buses"]

plt.figure(figsize=(10, 5))
plt.plot(df['Frame'], df['vehicle_count'], 'b.-', label="Traffic Flow")  # Correct column names
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Traffic Flow Over Time")
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
window_size = 10

df['smoothed_vehicle_count'] = df['vehicle_count'].rolling(window=window_size, min_periods=1).mean()

# Plot smoothed graph
plt.figure(figsize=(10, 5))
plt.plot(df['Frame'], df['smoothed_vehicle_count'], 'r-', label="Smoothed Traffic Flow")  # Smoothed line
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Smoothed Traffic Flow Over Time")
plt.legend()
plt.grid(True)
plt.show()

"""Load Data and inspect

"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/traffic_analysis (17).csv")  # Replace with actual dataset file

print(df.head())

# Check column names and missing values
print(df.info())
print(df.describe())

"""Aggregate total vehicle count"""

df['total_vehicles'] = df['Cars'] + df['Buses']

# Plot overall traffic trend
plt.figure(figsize=(12, 5))
plt.plot(df['Frame'], df['total_vehicles'], color='blue', alpha=0.7, label="Total Vehicles")
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Traffic Flow Over Time")
plt.legend()
plt.grid(True)
plt.show()

"""smoother trend"""

df['moving_avg'] = df['total_vehicles'].rolling(window=10).mean()  # Adjust window size as needed

plt.figure(figsize=(12, 5))
plt.plot(df['Frame'], df['total_vehicles'], color='lightgray', alpha=0.5, label="Raw Data")
plt.plot(df['Frame'], df['moving_avg'], color='red', label="Smoothed Trend (Moving Avg)")
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Smoothed Traffic Trend")
plt.legend()
plt.grid(True)
plt.show()

"""vehicle type distribution"""

plt.figure(figsize=(8, 5))
sns.histplot(df['Cars'], bins=20, kde=True, color='blue', label="Cars", alpha=0.6)
sns.histplot(df['Buses'], bins=20, kde=True, color='red', label="Buses", alpha=0.6)
plt.xlabel("Vehicle Count")
plt.ylabel("Frequency")
plt.title("Distribution of Cars vs. Buses")
plt.legend()
plt.show()

"""Correlation Analysis"""

corr_matrix = df[['Cars', 'Buses', 'total_vehicles']].corr()
plt.figure(figsize=(6, 4))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

"""Peak Traffic detection"""

# Find peak traffic time
peak_traffic = df[df['total_vehicles'] == df['total_vehicles'].max()]
print("Peak Traffic Frame:\n", peak_traffic)

"""Visualizing peak traffic frames"""

plt.figure(figsize=(12, 5))
plt.plot(df['Frame'], df['total_vehicles'], label="Total Vehicles", color='blue', alpha=0.7)
plt.scatter([954, 1087], [24, 24], color='red', s=100, label="Peak Traffic Points")
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Traffic Flow with Peak Frames Highlighted")
plt.legend()
plt.grid(True)
plt.show()

"""Check traffic before and after peak"""

# Extract surrounding frames (e.g., ±10 frames)
peak_window = df[(df['Frame'] >= 944) & (df['Frame'] <= 1097)]
plt.figure(figsize=(12, 5))
plt.plot(peak_window['Frame'], peak_window['total_vehicles'], label="Traffic Near Peak", color='orange')
plt.axvline(954, color='red', linestyle='--', label="Peak 1 (Frame 954)")
plt.axvline(1087, color='purple', linestyle='--', label="Peak 2 (Frame 1087)")
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Traffic Near Peak Frames")
plt.legend()
plt.grid(True)
plt.show()

"""Detecting periodic traffic peaks"""

import numpy as np
from scipy.signal import find_peaks

peaks, _ = find_peaks(df['total_vehicles'], height=20)  # Detect peaks above 20 vehicles

plt.figure(figsize=(12, 5))
plt.plot(df['Frame'], df['total_vehicles'], label="Total Vehicles", color='blue')
plt.scatter(df['Frame'][peaks], df['total_vehicles'][peaks], color='red', s=100, label="Detected Peaks")
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Traffic Peak Detection Over Time")
plt.legend()
plt.grid(True)
plt.show()

"""Traffic flow categorization"""

def categorize_traffic(count):
    if count < 10:
        return "Low"
    elif 10 <= count <= 20:
        return "Moderate"
    else:
        return "High"

df["Traffic_Level"] = df["total_vehicles"].apply(categorize_traffic)

traffic_summary = df["Traffic_Level"].value_counts()
print(traffic_summary)

"""Peak Traffic over time"""

plt.figure(figsize=(12, 5))
df.groupby("Traffic_Level")["Frame"].count().plot(kind="bar", color=["green", "orange", "red"])
plt.xlabel("Traffic Level")
plt.ylabel("Count of Frames")
plt.title("Distribution of Traffic Levels Over Time")
plt.grid(axis="y")
plt.show()

"""Avg Forecasting"""

df["MA_Traffic"] = df["total_vehicles"].rolling(window=10).mean()

plt.figure(figsize=(12, 5))
plt.plot(df["Frame"], df["total_vehicles"], label="Actual Traffic", color="blue", alpha=0.5)
plt.plot(df["Frame"], df["MA_Traffic"], label="Moving Average", color="red")
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Traffic Trend with Moving Average Forecast")
plt.legend()
plt.grid(True)
plt.show()

"""Anamoly Detection"""

from scipy.stats import zscore

df["zscore"] = zscore(df["total_vehicles"])
df["Anomaly"] = df["zscore"].apply(lambda x: "Yes" if abs(x) > 2 else "No")

# Visualizing anomalies
plt.figure(figsize=(12, 5))
plt.plot(df["Frame"], df["total_vehicles"], label="Traffic Flow", color="blue", alpha=0.5)
plt.scatter(df[df["Anomaly"] == "Yes"]["Frame"], df[df["Anomaly"] == "Yes"]["total_vehicles"],
            color="red", s=100, label="Anomalies")
plt.xlabel("Frame")
plt.ylabel("Vehicle Count")
plt.title("Anomaly Detection in Traffic Flow")
plt.legend()
plt.grid(True)
plt.show()

"""LSTM Model"""

!pip install tensorflow

y_pred = model.predict(X_test)

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Load dataset
df = pd.read_csv("/content/traffic_analysis (17).csv")


X = df[['Frame']].values
y = df[['Cars', 'Buses']].values

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()
X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y)

X_scaled = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

model = Sequential([
    LSTM(50, activation='relu', input_shape=(1, 1), return_sequences=True),
    LSTM(50, activation='relu', return_sequences=False),
    Dense(2)
])

model.compile(optimizer='adam', loss='mse')

history = model.fit(X_scaled, y_scaled, epochs=20, batch_size=8, validation_split=0.2, verbose=1)


model.save("traffic_lstm_model.h5")

print(f"Final Loss: {history.history['loss'][-1]}")
print(f"Validation Loss: {history.history['val_loss'][-1]}")

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = X_train
y_train = y_train

from sklearn.model_selection import train_test_split

# Assuming X contains features and y contains labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

test_loss = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}")


y_pred = model.predict(X_test)
print(y_pred[:10])

model.save("traffic_anomaly_model.keras")

from tensorflow.keras.models import load_model

# Load the saved model
model = load_model("traffic_anomaly_model.keras")

# Make predictions
predictions = model.predict(X_test)
print(predictions[:10])  # Display first 10 predictions

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder


y_cars = y[:, 0]
y_buses = y[:, 1]


label_encoder_cars = LabelEncoder()
y_cars_encoded = label_encoder_cars.fit_transform(y_cars)

label_encoder_buses = LabelEncoder()
y_buses_encoded = label_encoder_buses.fit_transform(y_buses)

y_encoded = np.stack((y_cars_encoded, y_buses_encoded), axis=1)


if len(X.shape) == 2:
    n_samples, n_features = X.shape
    n_timesteps = 1
    X = X.reshape(n_samples, n_timesteps, n_features)
else:
    n_samples, n_timesteps, n_features = X.shape


scaler = StandardScaler()
X_scaled = np.zeros_like(X)

for i in range(n_features):
    X_scaled[:, :, i] = scaler.fit_transform(X[:, :, i])


X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)


print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

"""Train the model"""

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, r2_score

data = pd.read_csv('/content/traffic_analysis (17).csv')

data.columns = [col.strip().lower() for col in data.columns]
required_columns = {'cars', 'buses'}
if not required_columns.issubset(data.columns):
    raise KeyError(f"Missing columns in dataset: {required_columns - set(data.columns)}")

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data[['cars', 'buses']])


def create_sequences(data, time_steps=20):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i:i+time_steps])
        y.append(data[i+time_steps])
    return np.array(X), np.array(y)

X, y = create_sequences(data_scaled)
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]


X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 2)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 2)


model = Sequential([
    Bidirectional(LSTM(128, return_sequences=True, input_shape=(20, 2))),
    BatchNormalization(),
    Dropout(0.2),
    Bidirectional(LSTM(64, return_sequences=False)),
    BatchNormalization(),
    Dropout(0.2),
    Dense(2)
])

optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mae')

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)


history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test), verbose=1, callbacks=[early_stopping])


y_pred = model.predict(X_test)
y_test_rescaled = scaler.inverse_transform(y_test)
y_pred_rescaled = scaler.inverse_transform(y_pred)

mae_cars = mean_absolute_error(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])
mae_buses = mean_absolute_error(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])
r2_cars = r2_score(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])
r2_buses = r2_score(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])

print(f"\U0001F697 Mean Absolute Error for Cars: {mae_cars:.2f}")
print(f"\U0001F68C Mean Absolute Error for Buses: {mae_buses:.2f}")
print(f"\U0001F4CA R² score for Cars: {r2_cars:.2f}")
print(f"\U0001F4CA R² score for Buses: {r2_buses:.2f}")

import tensorflow as tf
tf.config.set_visible_devices([], 'GPU')  # Disable GPU

from google.colab import drive
drive.mount('/content/drive')

!mv "/content/traffic video.avi" "/content/drive/My Drive/"
!mv "/content/traffic video.mp4" "/content/drive/My Drive/"

import shutil
import os


model.save('traffic_lstm_model.h5')


base_dir_abs_path = os.path.abspath('traffic_lstm_model.h5')


shutil.make_archive(
    '/content/traffic_lstm_model',
    'zip',
    root_dir='/content/',
    base_dir=base_dir_abs_path
)

from google.colab import files
files.download('/content/traffic_lstm_model.zip')

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

import numpy as np

print("y_train class distribution:")
print(np.sum(y_train, axis=0))

print("y_test class distribution:")
print(np.sum(y_test, axis=0))

import collections

print("y_train class distribution:", collections.Counter(y_train.flatten()))
print("y_test class distribution:", collections.Counter(y_test.flatten()))

import numpy as np

# Convert y_train and y_test to np.int64
y_train = np.array(y_train, dtype=np.int64)
y_test = np.array(y_test, dtype=np.int64)

import numpy as np

print("Unique labels in y_train:", np.unique(y_train))
print("Unique labels in y_test:", np.unique(y_test))

import numpy as np
from tensorflow.keras.utils import to_categorical

y_train = np.array(y_train, dtype=int)
y_test = np.array(y_test, dtype=int)


if len(y_train.shape) > 1:
    y_train = y_train[:, 0]
if len(y_test.shape) > 1:
    y_test = y_test[:, 0]


num_classes = 22


y_train = to_categorical(y_train, num_classes=num_classes)
y_test = to_categorical(y_test, num_classes=num_classes)

print("Shape of y_train after one-hot encoding:", y_train.shape)
print("Shape of y_test after one-hot encoding:", y_test.shape)

print("Original X_test shape:", X_test.shape)

print("Original X_train shape:", X_train.shape)

print("Original X_test shape:", X_test.shape)

import numpy as np

X_train = np.repeat(X_train, 10, axis=1)
print(X_train.shape)

X_test = np.expand_dims(X_test, axis=-1)
print(X_test.shape)

print("X_test shape:", X_test.shape)
print("Expected input shape:", model.input_shape)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train original shape:", y_train.shape)
print("y_test original shape:", y_test.shape)

print("Current y_train shape:", y_train.shape)
print("Total elements in y_train:", y_train.size)

y_train = y_train.reshape(y_train.shape[0], -1)
y_test = y_test.reshape(y_test.shape[0], -1)

y_train = y_train[:, :2]  # Take only the first 2 columns
y_test = y_test[:, :2]  # Take only the first 2 columns

print("Final y_train shape:", y_train.shape)
print("Final y_test shape:", y_test.shape)

from collections import Counter


y_train_labels = np.argmax(y_train, axis=1)
y_test_labels = np.argmax(y_test, axis=1)

print("y_train class distribution:", Counter(y_train_labels))
print("y_test class distribution:", Counter(y_test_labels))

print("Original X_test shape:", X_test.shape)

print("X shape:", X.shape)
print("y shape:", y.shape)

"""Fixing the shape mismatch"""

min_samples = min(len(X), len(y))
X = X[:min_samples]
y = y[:min_samples]

"""Reshape data properly"""

X = X.values.reshape(-1, 1, 1)
print("New X shape:", X.shape)

"""split data properly"""

y = y[:112]  # Keep only the first 112 samples to match X

from sklearn.model_selection import train_test_split


min_samples = min(len(X), len(y))
X = X[:min_samples]
y = y[:min_samples]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Fixed X_train shape:", X_train.shape)
print("Fixed X_test shape:", X_test.shape)
print("Fixed y_train shape:", y_train.shape)
print("Fixed y_test shape:", y_test.shape)

print("y_train dtype:", y_train.dtype)
print("y_test dtype:", y_test.dtype)

"""Convert y_train and y_test to Integer Labels"""

y_train = y_train.astype(int)
y_test = y_test.astype(int)

"""One-hot encode y_train and y_test"""

print("Unique values in y_train:", np.unique(y_train))
print("Unique values in y_test:", np.unique(y_test))

print("y_train shape:", y_train.shape)
print("Unique values in y_train:", np.unique(y_train))

print("y_test shape:", y_test.shape)
print("Unique values in y_test:", np.unique(y_test))

# Flatten y_train and y_test if they are 2D
y_train = y_train.flatten()
y_test = y_test.flatten()


print("Fixed y_train shape:", y_train.shape)
print("Fixed y_test shape:", y_test.shape)

from tensorflow.keras.utils import to_categorical

num_classes = np.max(y_train) + 1
print("Number of classes:", num_classes)

y_train = to_categorical(y_train, num_classes=int(num_classes))
y_test = to_categorical(y_test, num_classes=int(num_classes))

print("New y_train shape:", y_train.shape)
print("New y_test shape:", y_test.shape)

print("Unique values in y_train:", np.unique(np.argmax(y_train, axis=1)))
print("Unique values in y_test:", np.unique(np.argmax(y_test, axis=1)))

"""One-Hot Encode"""

print("Original y_train values:", np.unique(y_train))
print("Original y_test values:", np.unique(y_test))

import numpy as np
from tensorflow.keras.utils import to_categorical

# Convert labels to integer type (if needed)
y_train = np.array(y_train, dtype=int).flatten()
y_test = np.array(y_test, dtype=int).flatten()

# Ensure labels start from 0 (only if needed)
min_label = np.min(y_train)
if min_label != 0:
    print("Shifting labels to start from 0...")
    y_train -= min_label
    y_test -= min_label

# Get correct num_classes
num_classes = np.max(y_train) + 1

# One-hot encode
y_train = to_categorical(y_train, num_classes=num_classes)
y_test = to_categorical(y_test, num_classes=num_classes)

# Verify encoding
print("New y_train shape:", y_train.shape)
print("New y_test shape:", y_test.shape)
print("Unique values in y_train after encoding:", np.unique(np.argmax(y_train, axis=1)))
print("Unique values in y_test after encoding:", np.unique(np.argmax(y_test, axis=1)))

print("y_train shape:", y_train.shape, "dtype:", y_train.dtype)
print("y_test shape:", y_test.shape, "dtype:", y_test.dtype)
print("y_train sample:\n", y_train[:5])

print("Fixed y_train shape:", y_train.shape)
print("Fixed y_test shape:", y_test.shape)
print("y_train sample:\n", y_train[:5])

from collections import Counter
y_train_labels = [tuple(row) for row in y_train]  # Convert rows to tuples
y_test_labels = [tuple(row) for row in y_test]
print("y_train class distribution:", Counter(y_train_labels))
print("y_test class distribution:", Counter(y_test_labels))

model.add(Dense(4, activation='softmax'))  # 4-class one-hot encoding

import numpy as np
y_train_classes = np.argmax(y_train, axis=1)  # Converts one-hot to class index
y_test_classes = np.argmax(y_test, axis=1)
print("y_train class indices:", Counter(y_train_classes))
print("y_test class indices:", Counter(y_test_classes))

"""convert labels to integers"""

import numpy as np
y_train_classes = np.argmax(y_train, axis=1)  # Converts one-hot to class index
y_test_classes = np.argmax(y_test, axis=1)
print("y_train class indices:", Counter(y_train_classes))
print("y_test class indices:", Counter(y_test_classes))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print("Before encoding:")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

from sklearn.model_selection import train_test_split

# Assuming X and y are properly shaped before splitting
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

print("After splitting:")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

print("y_train original shape:", y_train.shape)
print("y_test original shape:", y_test.shape)

y_train = y_train.astype(int)
y_test = y_test.astype(int)

num_classes = np.max(y_train) + 1  # Ensure correct class count
y_train = to_categorical(y_train, num_classes=num_classes)
y_test = to_categorical(y_test, num_classes=num_classes)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

y_train = y_train.reshape(y_train.shape[0], -1)  # (89, 12)
y_test = y_test.reshape(y_test.shape[0], -1)  # (23, 12)

num_classes = np.max(y_train) + 1  # Ensure the correct number of classes
print("Updated num_classes:", num_classes)

y_train = to_categorical(y_train, num_classes=num_classes)
y_test = to_categorical(y_test, num_classes=num_classes)

print("Fixed y_train shape:", y_train.shape)
print("Fixed y_test shape:", y_test.shape)
print("Unique values after encoding:", np.unique(np.argmax(y_train, axis=1)))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("y_train shape before encoding:", y_train.shape)

y_train_classes = y_train
y_test_classes = y_test

print("Original y_train shape:", y_train.shape)
print("Original y_test shape:", y_test.shape)

import numpy as np
from tensorflow.keras.utils import to_categorical

num_classes = 12  # Based on max y value

# Remove extra dimensions (Flatten to (89, 12))
y_train = np.argmax(y_train, axis=1)
y_test = np.argmax(y_test, axis=1)

# Apply one-hot encoding correctly
y_train_classes = to_categorical(y_train, num_classes=num_classes)
y_test_classes = to_categorical(y_test, num_classes=num_classes)

print("Fixed y_train_classes shape:", y_train_classes.shape)  # Should be (89, 12)
print("Fixed y_test_classes shape:", y_test_classes.shape)  # Should be (23, 12)

assert X_train.shape[0] == y_train_classes.shape[0], "Mismatch in training data size!"
assert X_test.shape[0] == y_test_classes.shape[0], "Mismatch in testing data size!"

"""update output layer"""

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

num_classes = 12  # Ensure this matches the encoded labels

model = Sequential([
    # Your existing layers...
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')  # Fix here!
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

"""Add flatten before the final step layer"""

from tensorflow.keras.layers import Flatten

model.add(Flatten())  # Convert (None, 10, 12) -> (None, 120)
model.add(Dense(12, activation='softmax'))  # Ensure final shape is (None, 12)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

model = Sequential([
    Dense(128, activation='relu', input_shape=(10,)),  # Change input shape
    Dense(64, activation='relu'),
    Dense(12, activation='softmax')  # Final output (None, 12)
])

print(y_train_classes.shape)  # Should be (None, 12)
print(model.output_shape)  # Should be (None, 12)

# Assuming X_train has the shape (batch_size, 128)
X_train = X_train.reshape(X_train.shape[0], 10, 1)  # Reshape to (batch_size, 10, 1)

import numpy as np

X_train = X_train.reshape(-1, 10, 1)

print("New X_train shape:", X_train.shape)

print("Before reshaping:", X_train.shape)

X_train_reshaped = X_train[:, :, 0].reshape(-1, 1, 1)

print("After reshaping:", X_train_reshaped.shape)

from keras.models import Sequential
from keras.layers import LSTM, Dense, Input

model = Sequential()
model.add(Input(shape=(1, 1)))
model.add(LSTM(units=64))
model.add(Dense(1))

print(X_train.shape)

print(y_train.shape)

print(np.unique(y_train))

# Check the first few rows and column names of the CSV
import pandas as pd

df = pd.read_csv('/content/traffic_analysis (17).csv')
print(df.head())  # Show the first few rows
print(df.columns)  # Print the column names

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error


df = pd.read_csv('/content/traffic_analysis (17).csv')


X = df[['Frame']]
y_cars = df['Cars']
y_buses = df['Buses']

# Split dataset into training and testing sets
X_train, X_test, y_train_cars, y_test_cars = train_test_split(X, y_cars, test_size=0.2, random_state=42)
X_train, X_test, y_train_buses, y_test_buses = train_test_split(X, y_buses, test_size=0.2, random_state=42)

# Create and train the model for Cars
model_cars = RandomForestRegressor(n_estimators=100, random_state=42)
model_cars.fit(X_train, y_train_cars)

# Create and train the model for Buses
model_buses = RandomForestRegressor(n_estimators=100, random_state=42)
model_buses.fit(X_train, y_train_buses)


y_pred_cars = model_cars.predict(X_test)
y_pred_buses = model_buses.predict(X_test)


mse_cars = mean_squared_error(y_test_cars, y_pred_cars)
mse_buses = mean_squared_error(y_test_buses, y_pred_buses)

print(f'Mean Squared Error for Cars Prediction: {mse_cars}')
print(f'Mean Squared Error for Buses Prediction: {mse_buses}')


import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(y_test_cars.values, label='True Cars')
plt.plot(y_pred_cars, label='Predicted Cars')
plt.title('Cars Prediction')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(y_test_buses.values, label='True Buses')
plt.plot(y_pred_buses, label='Predicted Buses')
plt.title('Buses Prediction')
plt.legend()

plt.show()

early_stopping = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import matplotlib.pyplot as plt


df = pd.read_csv('/content/traffic_analysis (17).csv')


df = df[['Frame', 'Cars', 'Buses']]


scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df[['Cars', 'Buses']])

def create_sequences(data, time_step=1):
    X, y = [], []
    for i in range(len(data) - time_step):
        X.append(data[i:(i + time_step), 0:2])
        y.append(data[i + time_step, 0:2])
    return np.array(X), np.array(y)


train_data, test_data = train_test_split(scaled_data, test_size=0.2, shuffle=False)


time_step = 10
X_train, y_train = create_sequences(train_data, time_step)
X_test, y_test = create_sequences(test_data, time_step)

# Reshape data to match LSTM input shape
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 2)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 2)

# Build the LSTM model
model = Sequential()
model.add(LSTM(units=50, return_sequences=False, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dense(units=2))  # Output layer for cars and buses
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))
y_pred = model.predict(X_test)


y_test_rescaled = scaler.inverse_transform(y_test)
y_pred_rescaled = scaler.inverse_transform(y_pred)

# Evaluate model performance
from sklearn.metrics import mean_squared_error
mse_cars = mean_squared_error(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])  # Cars MSE
mse_buses = mean_squared_error(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])  # Buses MSE

print(f'Mean Squared Error for Cars Prediction: {mse_cars}')
print(f'Mean Squared Error for Buses Prediction: {mse_buses}')

# Plot the results for Cars and Buses
plt.figure(figsize=(14, 6))


plt.subplot(1, 2, 1)
plt.plot(y_test_rescaled[:, 0], label='True Cars')
plt.plot(y_pred_rescaled[:, 0], label='Predicted Cars')
plt.title('Cars Prediction')
plt.legend()


plt.subplot(1, 2, 2)
plt.plot(y_test_rescaled[:, 1], label='True Buses')
plt.plot(y_pred_rescaled[:, 1], label='Predicted Buses')
plt.title('Buses Prediction')
plt.legend()

plt.show()

"""Traffic flow prediction model(Bidirectioanl LSTM)"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Bidirectional
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping


data = pd.read_csv('/content/traffic_analysis (17).csv')


scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data[['Cars', 'Buses']])


def create_sequences(data, time_step=5):
    X, y = [], []
    for i in range(time_step, len(data)):
        X.append(data[i-time_step:i, :])
        y.append(data[i, :])
    return np.array(X), np.array(y)
time_step = 10
X, y = create_sequences(scaled_data, time_step)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)


model = Sequential()
model.add(Bidirectional(LSTM(units=64, return_sequences=True), input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Bidirectional(LSTM(units=32, return_sequences=False)))
model.add(Dense(2))

model.compile(optimizer='adam', loss='mean_squared_error')


early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), callbacks=[early_stopping])


y_pred = model.predict(X_test)


y_pred_rescaled = scaler.inverse_transform(y_pred)
y_test_rescaled = scaler.inverse_transform(y_test)


from sklearn.metrics import mean_squared_error
mse_cars = mean_squared_error(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])
mse_buses = mean_squared_error(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])

print(f"Mean Squared Error for Cars: {mse_cars}")
print(f"Mean Squared Error for Buses: {mse_buses}")

"""Accuracy evaluation"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/traffic_analysis (17).csv")


X = df.iloc[:, :-2].values
y = df.iloc[:, -2:].values

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()
X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

time_steps = 1
X_train = X_train.reshape(X_train.shape[0], time_steps, X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0], time_steps, X_test.shape[1])


model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(time_steps, X_train.shape[2])),
    Dropout(0.2),
    LSTM(32, return_sequences=False),
    Dropout(0.2),
    Dense(2)
])

model.compile(loss="mse", optimizer="adam")
model.summary()


model.fit(X_train, y_train, epochs=10, batch_size=16, validation_data=(X_test, y_test))


y_pred = model.predict(X_test)


y_pred_rescaled = scaler_y.inverse_transform(y_pred)
y_test_rescaled = scaler_y.inverse_transform(y_test)


mae_cars = mean_absolute_error(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])
mae_buses = mean_absolute_error(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])

r2_cars = r2_score(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])
r2_buses = r2_score(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])

print(f" Mean Absolute Error for Cars: {mae_cars:.2f}")
print(f" Mean Absolute Error for Buses: {mae_buses:.2f}")
print(f" R² score for Cars: {r2_cars:.2f}")
print(f" R² score for Buses: {r2_buses:.2f}")

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, r2_score

# Load dataset
data = pd.read_csv('/content/traffic_analysis (17).csv')


data.columns = [col.strip().lower() for col in data.columns]

required_columns = {'cars', 'buses'}
if not required_columns.issubset(data.columns):
    raise KeyError(f"Missing columns in dataset: {required_columns - set(data.columns)}")

# Preprocess data
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data[['cars', 'buses']])

def create_sequences(data, time_steps=20):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i:i+time_steps])
        y.append(data[i+time_steps])
    return np.array(X), np.array(y)

X, y = create_sequences(data_scaled)
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Build model
model = Sequential([
    LSTM(128, return_sequences=True, input_shape=(20, 2)),
    Dropout(0.3),
    LSTM(64, return_sequences=True),
    Dropout(0.3),
    LSTM(32, return_sequences=False),
    Dropout(0.3),
    Dense(2)
])

model.compile(optimizer='adam', loss='mse')

# Train model
history = model.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test), verbose=1)

# Predictions
y_pred = model.predict(X_test)
y_test_rescaled = scaler.inverse_transform(y_test)
y_pred_rescaled = scaler.inverse_transform(y_pred)

# Evaluate
mae_cars = mean_absolute_error(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])
mae_buses = mean_absolute_error(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])
r2_cars = r2_score(y_test_rescaled[:, 0], y_pred_rescaled[:, 0])
r2_buses = r2_score(y_test_rescaled[:, 1], y_pred_rescaled[:, 1])

print(f"\U0001F697 Mean Absolute Error for Cars: {mae_cars:.2f}")
print(f"\U0001F68C Mean Absolute Error for Buses: {mae_buses:.2f}")
print(f"\U0001F4CA R² score for Cars: {r2_cars:.2f}")
print(f"\U0001F4CA R² score for Buses: {r2_buses:.2f}")

"""Monitoring training progress"""

import matplotlib.pyplot as plt

# Assuming `history` is your training history
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.legend()
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.show()

"""Visualize prediction vs actual loss"""

import matplotlib.pyplot as plt

y_test_flat = y_test.reshape(-1)
y_pred_flat = y_pred.reshape(-1)

plt.scatter(range(len(y_test_flat)), y_test_flat, label="Actual", alpha=0.7)
plt.scatter(range(len(y_pred_flat)), y_pred_flat, label="Predicted", alpha=0.7, color='orange')
plt.legend()
plt.show()